# Generated by Django 3.2 on 2023-07-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_piezasrepuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('codigo', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidad', models.CharField(max_length=20)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cotizacion')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.piezasrepuesto')),
            ],
        ),
    ]
