# Generated by Django 3.2 on 2023-07-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_descripcioncotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcioncotizacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
