# Generated by Django 3.2 on 2023-08-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_descripcioncotizacion_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcioncotizacion',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
